---
stages:
  - build
  - promote

images:
  stage: build
  image: quay.io/containers/buildah
  script:
    - buildah bud --tag "$CI_REGISTRY_IMAGE" --file "${CI_PROJECT_DIR}/Dockerfile" $CI_PROJECT_DIR
    - buildah push --creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" "$CI_REGISTRY_IMAGE" "docker://${CI_REGISTRY_IMAGE}"
  only:
    - master
  variables:
    _BUILDAH_STARTED_IN_USERNS: ''
    BUILDAH_ISOLATION: chroot
    BUILDAH_FORMAT: docker
    STORAGE_DRIVER: vfs

promote:
  stage: promote
  image: ${CI_REGISTRY_IMAGE}:latest
  script:
    - /skopeo copy --src-creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" --dest-creds "${PROMOTE_USER}:${PROMOTE_PASS}" "docker://${CI_REGISTRY_IMAGE}:latest" "docker://${PROMOTE_IMAGE}:latest"
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - master
    variables:
      - $PROMOTE_USER
      - $PROMOTE_PASS
      - $PROMOTE_REGISTRY
      - $PROMOTE_IMAGE
